


Map<String,String> m = {

  "WELCOME" : "Selamat Datang",
  "Registered Successfully" : "Pendaftaran Berjaya",
  "Login" : "Log Masuk",
  "LOGIN" : "LOG MASUK",
  "Sign Up" : "Daftar",
  "Signup": "Pendaftaran",
  "First Name": "Nama Pertama",
  "Last Name" : "Nama Terakhir",
  "Address" : "Alamat",
  "Mobile No." : "Nombor Telefon",
  "License No." : "Nombor Lesen",
  "NRIC": "Nombor Kad Pengenalan",
  "Bank Account No." : "Nombor Akaun Bank",
  "Make" : "Jenama Kenderaan",
  "Model No." : "Nombor/Tahun Model",
  "Registration No." : "Nombor Pendaftaran",
  "Next" : "Seterusnya",
  "Credentials" : "Maklumat Akaun",
  "Email": "Emel",
  "Password":"Kata Laluan",
  "Forgot Password": "lupa kata laluan",
  "Confirm Password":"Sahkan Kata Laluan",
  "Note":"Catatan: Kata laluan mesti mengandungi nombor, watak khas dan huruf besar.",
  "Home":"Kembali",
  "HOME":"KEMBALI",
  "Thank You!":"Terima Kasih!",
  "Order Completed":"Pesanan Selesai",
  "Confirm Items":"Sahkan Barangan",
  "CONFIRM ITEMS":"SAHKAN BARANGAN",
  "Product Name":"Nama Produk",
  "Quantity":"Kuantiti",
  "Select All":"Pilih Semua",
  "Deselect":"Nyahpilih  ",
  "Done":"Selesai",
  "Deselect All":"Nyahpilih Semua",
  "ORDER DETAILS" : "Maklumat Pesanan",
  "Order Details" : "Maklumat Pesanan",
  "Order Number" : "Nombor Pesanan",
  "Product Detail" : "Maklumat Produk",
  "Store" : "Cawangan",
  "Total" : "Jumlah",
  "Delivery Charges" : "Caj Penghantaran",
  "Grand Total" : "Jumlah Keseluruhan",
  "Delivery" : "Hantar Pada",
  "Addresses" : "Alamat",
  "Navigate" : "Navigasi",
  "Pickup" : "Ambil Di",
  "Pickup Time" : "Ambil Dalam Masa",
  "Expand" : "Kembangkan",
  "Order Status" : "Status Pesanan",
  "Accepted" : "Diterima",
  "Picked" : "Telah Diambil",
  "Delivered" : "Berjaya Dihantar",
  "Mark Delivered" : "Berjaya Dihantar",
  "Orders" : "Pesanan",
  "Dashboard" : "Papan Pemuka",
  "Profile" : "Profil",
  "Logout" : "Log Keluar",
  "Items" : "Barangan",
  "Details" : "Lebih Maklumat",
  "Order Items" : "Barangan",
  "Earning This Month" : "Pendapatan Bulan Ini",
  "Orders This Month" : "Jumlah Pesanan Bulan Ini",
  "Basic Details" : "Maklumat Asas",
  "Vehicle Details" : "Maklumat Kenderaan",
  "Security" : "Keselamatan",
  "Terms & Conditions" : " Terma & Syarat",
  "I agree with" : " Saya bersetuju dengan",
  "stated." : " yang dinyatakan.",
  "No internet": "Tiada internet",
  "Something went wrong, please try again later": "Terdapat masalah, sila cuba sebentar lagi",
  "Are you sure you want to exit Application?": "Adakah anda pasti hendak keluar dari Aplikasi ?",
  "No": "Tidak",
  "Yes": "Ya",
  "Go online and start picking up Orders": "Sila pergi online dan mula mengambil Pesanan",
  "Please turn on Wifi or Mobile Data": "Sila hidupkan Wifi atau Data Mudah Alih",
  "Invalid credentials!": "Kelayakan tidak sah",
  "Password must be 6 characters long": "Kata laluan mestilah 6 aksara panjang",
  "Password and Confirm Password doesn’t match": "Kata laluan dan Kata Laluan Sekali Lagi tidak sepadan",
  "Please Enter Email": "Sila Masukkan Emel",
  "Please Enter Password": "Sila Masukkan Kata Laluan",
  "Please Enter Confirm Password": "Sila Masukkan Kata Laluan Sekali Lagi",
  "Please Enter Make": "Sila Masukkan Jenama Kenderaan",
  "Please Enter Model No.": "Sila Masukkan No. Model",
  "Please Enter Registration No.": "Sila Masukkan No. Pendaftaran",
  "Please Enter First Name": "Sila Masukkan Nama Awal",
  "Please Enter Last Name": "Sila Masukkan Nama Akhi",
  "Please Enter Mobile No.": "Sila Masukkan No. Telefon",
  "Please Enter Licence No.": "Sila Masukkan No. Lesen",
  "Please Enter Address": "Sila Masukkan Alamat",
  "Please Enter NRIC": "Sila masukkan NRIC",
  "Please Enter Bank Account No.": "Sila Masukkan No. Bank Akaun",
  "Select Image (NRIC)": "Pilih Imej (NRIC)",
  "Select Image (Licence)": "Pilih Imej (Lesen)",
  "Please select NRIC image": "Sila pilih imej NRIC",
  "Please select profile image": "Sila pilih imej profil",


};